# Translation of the js protocol.js file of the server
RESET_SEQUENCE = 0
RESET_SEQUENCE_AWK = 1
CLIENT_TO_SERVER_MESSAGE = 2
SERVER_TO_CLIENT_MESSAGE = 3
PING = 4
SYNC = 5
AWK_MESSAGE_SEQUENCE = 6
ASSIGN_SESSION = 7
SET_SESSION = 8
AWK_MISC = 9

ENCODING = "utf-8"